language: node_js
node_js:
  - "12"
deploy:
  - provider: script
    script:
      - npx vercel --prod --confirm --token $VERCEL_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script:
     - npx semantic-release@17
    skip_cleanup: true
    on:
      branch: master
after_deploy:
  - node scripts/update-hooks.js
  - node scripts/superfeedr/update-subscriptions.js
