language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_install:
  - npm install -g vercel
deploy:
  - provider: script
    script: vercel --prod --confirm --token $VERCEL_TOKEN
    skip_cleanup: true
    on:
      branch: master
