language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_deploy:
  - npm install -g vercel
deploy:
  - provider: script
    script: vercel --prod --confirm --token $VERCEL_TOKEN
    on:
      branch: master
after_deploy:
  - provider: script
    script: node scripts/update-hooks.js
    on:
      branch: master
